### ISSUE TITLE
Generate 2 or more unique ids under same roof how?

### ISSUE THREAD

**Issue by wazerstar** [lolPants/caddy-requestid#2]
I have to rewrite and give a session and client id if I add it like this

rewrite * /p{path}?Client={http.request_id}?Session={http.request_id}&{query}

It will show the same id in client and session, I would like to have the outcome be completely different this request.

I could do some hacky by just adding a extra number in the example Session ?SessionID=**1**{http.request_id}&{query}

So this it will become, but still not really like this method.

rewrite * /p{path}?ClientID={http.request_id}?SessionID=1{http.request_id}&{query}

**Comment by luludotdev** [comment]
Closed as of 359dcf929bb9f8b40484247add8c3f0ed30dcb6a.
The lib has been rewritten under the hood to support multiple IDs. See the readme for examples.

**Comment by wazerstar** [comment]
> Closed as of [359dcf9](https://github.com/lolPants/caddy-requestid/commit/359dcf929bb9f8b40484247add8c3f0ed30dcb6a). The lib has been rewritten under the hood to support multiple IDs. See the readme for examples.

Thanks, tho When I test with sample with caddy file header is empty and so is body, I did redownload from https://caddyserver.com/download and selected your plugin, any figs?

**Comment by luludotdev** [comment]
Forgot to tag a release, whoops. You can either force version `v1.1.0` in the caddy download page or wait for the go package cache to recognise that as the latest.
